import React from 'react';

/**
 * Renders the SummaryResult generated by analysis/summary.
 * Display order:
 * 1. Overall Assessment
 * 2. Signal Statistics
 * 3. Evidence
 * 4. Limitations
 */
export default function SummaryCard({ summary }) {
  if (!summary) return null;

  // Support string fallback or full SummaryResult object
  const isObjectSummary = typeof summary === 'object' && summary !== null;
  
  if (!isObjectSummary && typeof summary === 'string') {
    return (
      <div className="bg-indigo-950/30 border border-indigo-800/40 rounded-xl p-3.5 my-3 text-xs text-slate-300">
        {summary}
      </div>
    );
  }

  const {
    overallAssessment = 'No summary available.',
    statistics = { totalReviews: 0, ratingMismatches: 0, duplicateReviews: 0, verifiedPurchases: 0 },
    evidence = [],
    limitations = [],
  } = summary;

  return (
    <div className="bg-slate-800/40 border border-slate-700/50 rounded-xl p-4 my-3 space-y-4">
      {/* 1. Overall Assessment */}
      <div>
        <h4 className="text-[11px] font-bold text-indigo-400 uppercase tracking-wider mb-1">
          Overall Assessment
        </h4>
        <div className="text-xs font-medium text-slate-200 bg-indigo-950/40 border border-indigo-800/50 rounded-lg p-2.5">
          {overallAssessment}
        </div>
      </div>

      {/* 2. Signal Statistics */}
      <div>
        <h4 className="text-[11px] font-bold text-slate-400 uppercase tracking-wider mb-2">
          Signal Statistics
        </h4>
        <div className="grid grid-cols-2 gap-2 text-xs">
          <div className="bg-slate-900/60 border border-slate-700/40 rounded-lg p-2 flex flex-col">
            <span className="text-[10px] text-slate-400">Total Reviews</span>
            <span className="font-semibold text-slate-200 mt-0.5">{statistics.totalReviews}</span>
          </div>
          <div className="bg-slate-900/60 border border-slate-700/40 rounded-lg p-2 flex flex-col">
            <span className="text-[10px] text-slate-400">Rating Mismatches</span>
            <span className="font-semibold text-amber-300 mt-0.5">{statistics.ratingMismatches}</span>
          </div>
          <div className="bg-slate-900/60 border border-slate-700/40 rounded-lg p-2 flex flex-col">
            <span className="text-[10px] text-slate-400">Duplicate Reviews</span>
            <span className="font-semibold text-rose-300 mt-0.5">{statistics.duplicateReviews}</span>
          </div>
          <div className="bg-slate-900/60 border border-slate-700/40 rounded-lg p-2 flex flex-col">
            <span className="text-[10px] text-slate-400">Verified Purchases</span>
            <span className="font-semibold text-emerald-300 mt-0.5">{statistics.verifiedPurchases}</span>
          </div>
        </div>
      </div>

      {/* 3. Evidence */}
      {evidence.length > 0 && (
        <div>
          <h4 className="text-[11px] font-bold text-slate-400 uppercase tracking-wider mb-1.5">
            Evidence
          </h4>
          <ul className="space-y-1 pl-4 list-disc text-xs text-slate-300">
            {evidence.map((item, idx) => (
              <li key={idx} className="leading-normal">{item}</li>
            ))}
          </ul>
        </div>
      )}

      {/* 4. Limitations */}
      {limitations.length > 0 && (
        <div>
          <h4 className="text-[11px] font-bold text-slate-400 uppercase tracking-wider mb-1.5">
            Limitations
          </h4>
          <ul className="space-y-1 pl-4 list-disc text-xs text-slate-400">
            {limitations.map((item, idx) => (
              <li key={idx} className="leading-normal">{item}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
